// Standard-Inhalte für den Demo-Modus.
// Im Live-Betrieb kommen dieselben Daten aus Supabase
// (siehe supabase/migrations/20260918000000_init.sql).

// Zweites Rad fürs Waffen-Lotto – auch Vorlage, wenn im Editor ein zweites Rad eingeschaltet wird
export const RARITY_WHEEL = {
  name: 'Seltenheit',
  segments: [
    { label: 'Gewöhnlich', detail: 'Nur die graue Version – kein Upgrade.', color: '#9aa3ad' },
    { label: 'Ungewöhnlich', detail: 'Nur die grüne Version.', color: '#3ddc84' },
    { label: 'Selten', detail: 'Nur die blaue Version.', color: '#35a7ff' },
    { label: 'Episch', detail: 'Nur die lila Version.', color: '#b45cff' },
    { label: 'Legendär', detail: 'Nur die goldene Version – such gut!', color: '#ffa928' },
    { label: 'Mythisch', detail: 'Mythisch oder Boss-Version – bis dahin jede Seltenheit.', color: '#ffd84a' },
  ],
};

export const DEFAULT_VARIANTS = [
  {
    id: 'waffen',
    position: 1,
    name: 'Waffen-Roulette',
    description: 'Bestimmt, womit der Streamer kämpfen darf.',
    color: '#ffb81c',
    segments: [
      { label: 'Nur Schrotflinten', detail: 'Nur Shotguns (und die Spitzhacke) sind erlaubt.' },
      { label: 'Nur Grau & Grün', detail: 'Nur Waffen der Seltenheit Gewöhnlich und Ungewöhnlich.' },
      { label: 'Erste Waffe zählt', detail: 'Die erste gefundene Waffe bleibt die einzige Waffe.' },
      { label: 'Pistolen & MPs', detail: 'Nur Pistolen und Maschinenpistolen.' },
      { label: 'Keine Shotguns', detail: 'Alles ist erlaubt – außer Schrotflinten.' },
      { label: 'Sniper-Pflicht', detail: 'Ein Scharfschützengewehr muss immer im Inventar sein.' },
      { label: 'Nur Truhen-Loot', detail: 'Nur Items aus Truhen, kein Boden-Loot.' },
      { label: 'Freie Wahl', detail: 'Glück gehabt: keine Waffen-Regel!' },
    ],
  },
  {
    id: 'landung',
    position: 2,
    name: 'Lande-Lotto',
    description: 'Entscheidet, wo und wie der Streamer in die Runde startet.',
    color: '#3ddc84',
    segments: [
      { label: 'Hot Drop', detail: 'Lande am vollsten POI der Runde.' },
      { label: 'Letzter raus', detail: 'Springe als Allerletzter aus dem Bus.' },
      { label: 'Erster raus', detail: 'Springe sofort beim ersten möglichen Moment ab.' },
      { label: 'Chat wählt', detail: 'Der Chat bestimmt den Landeort.' },
      { label: 'Höchster Punkt', detail: 'Lande auf dem höchsten Punkt in Reichweite.' },
      { label: 'Nur zu Fuß', detail: 'Keine Fahrzeuge in dieser Runde.' },
      { label: 'Straßenkind', detail: 'Lande so nah wie möglich an einer Straße.' },
      { label: 'Freie Wahl', detail: 'Glück gehabt: lande, wo du willst!' },
    ],
  },
  {
    id: 'handicap',
    position: 3,
    name: 'Handicap-Express',
    description: 'Eine Extra-Challenge für die ganze Runde.',
    color: '#9146ff',
    segments: [
      { label: 'Kein Heilen', detail: 'Keine Heil- oder Schild-Items benutzen.' },
      { label: 'Kein Sprinten', detail: 'Nur gehen – niemals sprinten.' },
      { label: 'Emote nach Kill', detail: 'Nach jedem Kill sofort ein Emote.' },
      { label: 'Nur 3 Slots', detail: 'Maximal drei Inventarplätze belegen.' },
      { label: 'Ducken im Kampf', detail: 'Im Kampf nur geduckt bewegen.' },
      { label: 'Kein Bauen', detail: 'Nicht bauen – auch nicht im Build-Modus.' },
      { label: 'Pazifist bis Top 10', detail: 'Keine Kämpfe, bis nur noch 10 Spieler übrig sind.' },
      { label: 'Freifahrt', detail: 'Glück gehabt: keine Challenge!' },
    ],
  },
  {
    // Zwei Räder hintereinander: erst die Waffe, dann die Seltenheit (bonus)
    id: 'waffen-lotto',
    position: 4,
    name: 'Waffen-Lotto',
    description: 'Lost die einzige Waffe des Streamers aus – danach dreht das Rad die Seltenheit.',
    color: '#ff5a4e',
    segments: [
      { label: 'Sturmgewehr', detail: 'Ein Sturmgewehr ist die einzige Waffe des Streamers.' },
      { label: 'Schrotflinte', detail: 'Eine Schrotflinte ist die einzige Waffe des Streamers.' },
      { label: 'Maschinenpistole', detail: 'Eine Maschinenpistole ist die einzige Waffe des Streamers.' },
      { label: 'Pistole', detail: 'Eine Pistole ist die einzige Waffe des Streamers.' },
      { label: 'Scharfschützengewehr', detail: 'Ein Scharfschützengewehr ist die einzige Waffe des Streamers.' },
      { label: 'Explosivwaffe', detail: 'Raketenwerfer, Granatwerfer & Co. – nur Explosives.' },
      { label: 'Bogen / Armbrust', detail: 'Ein Bogen oder eine Armbrust ist die einzige Waffe des Streamers.' },
      { label: 'Maschinengewehr', detail: 'Ein Maschinengewehr ist die einzige Waffe des Streamers.' },
    ],
    bonus: RARITY_WHEEL,
  },
];

// Zweites Rad einer Variante als eigenes Rad (gleiche Form wie eine Variante)
export const bonusWheel = (variant) => (variant?.bonus?.segments?.length
  ? { id: `${variant.id}:bonus`, name: variant.bonus.name, color: variant.color, segments: variant.bonus.segments }
  : null);

// Ergebnis einer Drehung als eine Zeile, z. B. „Sturmgewehr · Episch“
export const spinTitle = (spin) => (spin.bonus_result ? `${spin.result} · ${spin.bonus_result}` : spin.result);

export const DEFAULT_TILES = [
  {
    id: 'wheel',
    position: 1,
    kind: 'wheel',
    title: 'Fortnite-Glücksrad',
    description: 'Vier Varianten, die die nächste Runde des Streamers auf den Kopf stellen – beim Waffen-Lotto dreht danach noch die Seltenheit. Auch per Kanalpunkte direkt aus dem Chat drehbar.',
    theme: 'wheel',
    target_at: null,
    background: null,
  },
  {
    id: 'prank',
    position: 2,
    kind: 'prank',
    title: 'Ärgere den Streamer',
    description: 'Bananen, Tomaten, Torten – wirf was auf den Streamer oder spiel ihm deine eigenen Sounds in den Stream.',
    theme: 'prank',
    target_at: '2026-10-01T20:00:00+02:00',
    background: null,
  },
  {
    id: 'bingo',
    position: 3,
    kind: 'bingo',
    title: 'Fortnite-Bingo',
    description: 'Welche Items findet der Streamer diese Runde? Die Karte wird zufällig gezogen und im Stream abgehakt.',
    theme: 'bingo',
    target_at: '2026-10-01T20:00:00+02:00',
    background: null,
  },
  {
    id: 'questions',
    position: 4,
    kind: 'questions',
    title: 'Unangenehme Fragen',
    description: 'Stell dem Streamer die Fragen, die sich sonst keiner traut. Kneift er, gibt es eine Bestrafung – live im Stream.',
    theme: 'questions',
    target_at: '2026-10-01T20:00:00+02:00',
    background: null,
  },
  {
    id: 'pet',
    position: 5,
    kind: 'pet',
    title: 'Stream-Dino',
    description: 'Ein kleiner Dino wohnt im Stream. Füttere ihn – sonst knabbert er an den Zuschauern.',
    theme: 'pet',
    target_at: '2026-10-01T20:00:00+02:00',
    background: null,
  },
  {
    id: 'shop',
    position: 6,
    kind: 'shop',
    title: 'Kisten-Shop',
    description: 'Wähl eine Kiste, kauf dir mit den Goldbarren Items und finde sie im Spiel. Allein oder im Koop gegen andere.',
    theme: 'shop',
    target_at: '2026-10-05T00:00:00+02:00',
    background: null,
  },
  {
    id: 'challenge',
    position: 7,
    kind: 'challenge',
    title: 'Win-Challenge',
    description: 'Games, Runden und Fights gegen die Mods – schafft der Streamer alle Stufen, bevor ihm die Leben ausgehen?',
    theme: 'challenge',
    target_at: '2026-10-10T00:00:00+02:00',
    background: null,
  },
  {
    id: 'forbidden',
    position: 8,
    kind: 'forbidden',
    title: 'Verbotenes Wort',
    description: 'Ein Wort, das der Streamer nicht sagen darf. Erwischt? Schreib !erwischt – jeder Versprecher kostet eine Strafe.',
    theme: 'forbidden',
    target_at: null,
    background: null,
  },
  {
    id: 'subathon',
    position: 9,
    kind: 'subathon',
    title: 'Subathon',
    description: 'Jeder Follow, jedes Abo und jedes Bit verlängert den Stream. Wie lange hältst du ihn wach?',
    theme: 'subathon',
    target_at: null,
    background: null,
  },
  {
    id: 'pause',
    position: 10,
    kind: 'pause',
    title: 'Kurze Pause',
    description: 'Gleich geht’s weiter! Bis dahin: Zahlenraten im Chat mit !rate.',
    theme: 'pause',
    target_at: null,
    background: null,
  },
  {
    id: 'quiz',
    position: 11,
    kind: 'quiz',
    title: 'Fortnite-Quiz',
    description: 'Fragen im Stream, Antwort im Chat mit !a !b !c !d oder hier. Wer ist der größte Fortnite-Nerd?',
    theme: 'quiz',
    target_at: null,
    background: null,
  },
  {
    id: 'queue',
    position: 12,
    kind: 'queue',
    title: 'Mitspielen',
    description: 'Spiel mit dem Streamer! Stell dich mit !join und deinem Epic-Namen an.',
    theme: 'queue',
    target_at: null,
    background: null,
  },
  {
    id: 'tts',
    position: 13,
    kind: 'tts',
    title: 'Vorlesen lassen',
    description: 'Deine Nachricht, vorgelesen im Stream – mit Roboter-, Oma- oder Monster-Stimme.',
    theme: 'tts',
    target_at: null,
    background: null,
  },
  {
    id: 'cards',
    position: 14,
    kind: 'cards',
    title: 'Sammelkarten',
    description: 'Jeden Tag ein Gratis-Pack. Sammle alle Karten, tausche Doppelte und werde Nummer 1.',
    theme: 'cards',
    target_at: null,
    background: null,
  },
  {
    id: 'giveaway',
    position: 15,
    kind: 'giveaway',
    title: 'Verlosung',
    description: 'Ein Preis, ein Gewinner: Schreib !verlosung in den Chat und sei dabei. Jeder Follower darf einmal mitmachen.',
    theme: 'giveaway',
    target_at: null,
    background: null,
  },
  {
    id: 'hotwords',
    position: 16,
    kind: 'hotwords',
    title: 'Hot Words',
    description: 'Was schreibt der Chat am meisten? Die fünf heißesten Wörter stehen live im Stream – mit Zähler.',
    theme: 'hotwords',
    target_at: null,
    background: null,
  },
  {
    id: 'poll',
    position: 17,
    kind: 'poll',
    title: 'Umfrage',
    description: 'Der Chat entscheidet: Frage stellen, abstimmen im Panel unter dem Stream oder mit !vote im Chat.',
    theme: 'poll',
    target_at: null,
    background: null,
  },
  {
    id: 'counter',
    position: 18,
    kind: 'counter',
    title: 'Zähler',
    description: 'Tode, Kills, Versuche, Jumpscares – live im Stream. Mods zählen im Chat mit !tode +.',
    theme: 'counter',
    target_at: null,
    background: null,
  },
  {
    id: 'gamewheel',
    position: 19,
    kind: 'gamewheel',
    title: 'Spiel-Rad',
    description: 'Das Rad entscheidet: Welches Game kommt als Nächstes – oder welche Challenge gilt jetzt?',
    theme: 'gamewheel',
    target_at: null,
    background: null,
  },
  {
    id: 'heart',
    position: 20,
    kind: 'heart',
    title: 'Herzfrequenz',
    description: 'Wie sehr schwitzt der Streamer? Der Puls live im Stream – perfekt für Horror-Games.',
    theme: 'heart',
    target_at: null,
    background: null,
  },
  {
    id: 'idea-1',
    position: 21,
    kind: 'countdown',
    title: 'Late-Night-Marathon',
    description: 'Ein langer Stream bis tief in die Nacht – ohne Pause bis zum Finale.',
    theme: 'tracks',
    target_at: '2026-10-03T20:00:00+02:00',
    background: null,
  },
  {
    id: 'idea-4',
    position: 22,
    kind: 'countdown',
    title: 'Countdown zum Subathon',
    description: 'Der nächste Subathon kommt! Jeder Sub verlängert den Stream – wie lange geht es diesmal?',
    theme: 'city',
    target_at: '2026-11-21T12:00:00+01:00',
    background: null,
  },
];

// Vorschläge aus der Community (nur Demo-Modus – live kommen sie aus Supabase)
export const DEFAULT_IDEAS = [
  { id: 1, text: 'Late-Night-Horror mit Chat-Voting', author: 'pixelfuchs', votes: 42, voters: [] },
  { id: 2, text: 'Glücksrad mit Chat-Regeln', author: 'gg_sina', votes: 31, voters: [] },
  { id: 3, text: '24h-Stream mit Zuschauer-Challenges', author: 'loot_kev', votes: 18, voters: [] },
];
